### ISSUE TITLE
Scoped CSS: support mildly complex selectors

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/schlump#12]
> <input/> based mechanics are impossible to implement because they rely on the sibling selectors: + and ~

Handle style state in css in combintation with input fields (e.g. radio, checkbox) sibling selectors are required. Currently only simple selectors (one level) are supported.

Extension from #5 

## Selector Types
- [x] type selectors `div`
- [x] classname selectors `.classname`
- [x] descendant selector `div span` or `div >> span`
- [x] child selector `div > span`
- [x] next/adjacent sibling selectors `selector + selector`
- [x] general sibling selector `selector ~ selector`
- [x] ~id selectors `#id`~ nothing to do
- [x] ~attribute selectors `[attr]`~ defered to #31
- [x] ~pseudo class selectors `:hover`~ nothing to do
- [x] selector lists `type, .class`
- [x] ~universal selector `*`~ defered to #32 

## Combinations

- [x] `.class type`

**Comment by marionebl** [comment]
Picking up on the example from the docs it would be amazing if this would work:

```html
---
name: Element
---
<style scoped>
.element {
    color: blue;
}
.element h1 {
    color: green;
}
.element p {
  color: red;
}
.element h1 + .element p {
  color: magenta;
}
</style>
<div className={style.element}>
   Hey there!
    <h1>headline<h1>
    <p>
        copytext
    </p>
</div>
```

**Intended result**

```html
<div className="element-element">
   Hey there! <!-- blue -->
   <h1 className="element-element h1">headline</h1> <!-- green -->
   <p className="element-element p">copytext</p> <!-- magenta -->
</div>
```

**Comment by KnisterPeter** [comment]
That will lead to styling over component borders. I think you meant this one:

```html
---
name: Element
---
<style scoped>
.element {
    color: blue;
}
.element h1 {
    color: green;
}
.element p {
  color: red;
}
.element h1 + p {
  color: magenta;
}
</style>
<div className={style.element}>
   Hey there!
    <h1>headline<h1>
    <p>
        copytext
    </p>
</div>
```

**Intended result**

```css
.element-element {
    color: blue;
}
.element-h1 {
    color: green;
}
.element-p {
  color: red;
}
.element .element-h1 + .element-p {
  color: magenta;
}
```

```html
<div className="element-element">
   Hey there! <!-- blue -->
   <h1 className="element-h1">headline</h1> <!-- green -->
   <p className="element-p">copytext</p> <!-- magenta -->
</div>
```
