### ISSUE TITLE
Idea: Support some css-moduleish approach

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/schlump#3]
I think it would be super-nice to give schlump the capabilities to define styling inside of components. 
Perhaps this could lend concepts from `css-modules` or even CSS scoped styles.

css-modules
```js
---
name: Button
---
const style = css`
.button {
  display: inline-block;
  min-width: 175px;
  padding: 12px 24px;
  border: 2px solid currentColor;
  font-weight: bold;
  line-height: 40px;
  text-align: center;
}
`;
<a href={props.href} className={style.button}>
    {props.label}
</a>
```

"Scoped" styles
```html
---
name: Button
---
<style scoped>
.button {
  display: inline-block;
  min-width: 175px;
  padding: 12px 24px;
  border: 2px solid currentColor;
  font-weight: bold;
  line-height: 40px;
  text-align: center;
}
</style>
<a href={props.href} className={style.button}>
    {props.label}
</a>
```

**Comment by KnisterPeter** [comment]
I like the idea as well. I could also think of something like define css in a separate file but scope it the to the module as well.
The frontmatter could be used on css files as well.

**Comment by KnisterPeter** [comment]
After thinking about it the `everything in one file` approach should be taken I think.
