### ISSUE TITLE
How to reuse third party components

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/schlump#4]
Assuming I have a library of third-party components installed via `npm` and/or resolvable via `require.resolve`, how would i go about using them in schlump?

**Comment by KnisterPeter** [comment]
Currently it is not possible. There should be a way to resolve them. It should match to the current schlump style - like having everything in scope explicitly.

**Comment by marionebl** [comment]
To make implementation easy the feature could take its place in the frontmatter block. A possible notation could be an array of ES2015 import statements, e.g.:

```html
---
name: ButtonGroup
imports: 
  - import Root from 'node-module'
  - import {Button} from 'node-module'
---
<Root>
   <Button/>
   <Button/>
</Root>
```

**Comment by KnisterPeter** [comment]
I'm not sure about this. Frontmatter is more for meta data.

**Comment by marionebl** [comment]
@KnisterPeter: I added a second suggestion. That's basically what [patternplate-transform-react](https://github.com/sinnerschrader/patternplate-transform-react) does, though.

**Comment by KnisterPeter** [comment]
I would still favor the 'everything is global' simplicity of schlump and stick to that. At least we should give it a try.

**Comment by marionebl** [comment]
What would that look like for npm?

**Comment by KnisterPeter** [comment]
There need to be some 'import' statement. I thing its not very useful to import everything globally and just use everything which looks like react in a schlump page.
What I had in mind mir like a cli-option (e.g. `--templates-import <node-module-name>`)

**Comment by KnisterPeter** [comment]
Do you have a third-party library in mind where we could test something with?

**Comment by marionebl** [comment]
We could toy around with http://elemental-ui.com/

**Comment by KnisterPeter** [comment]
[This one](https://github.com/elementalui/elemental/blob/master/src/Elemental.js) would be a good candidate to import.
`--templates-import 'elemental'`

**Comment by KnisterPeter** [comment]
How about namespacing cli-imports? Like
`--templates-import 'elemental:UI'` and then ever elemental component could be used like this:
```
<Page>
  <UI.Button size="lg">Large Button</UI.Button>
</Page>
```

**Comment by marionebl** [comment]
So if i use a component library without default export this should work, too:

```js 
// imports.js
export default {
  Button,
  AnotherThing
};
```

```
schlump --templates-import './imports.js:UI'
```

```
<Page>
  <UI.Button size="lg">Large Button</UI.Button>
</Page>
```

**Comment by KnisterPeter** [comment]
The namespacing could be optional yes. Its the responsibility of the user to not have clashes. Schlump components (pages, and templates) would always win in case of a clash.
